/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitap_yayinciligi;

import java.util.ArrayList;

/**
 *
 * @author CASPER
 */
public class Kitap_Ekleme_Arayuz extends javax.swing.JFrame {

    /**
     * Creates new form Kitap_Ekleme_Arayuz
     */
    public Kitap_Ekleme_Arayuz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back_button = new javax.swing.JButton();
        back_combo_box = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kitabin_numarasi_label = new javax.swing.JLabel();
        kitabin_adi_label = new javax.swing.JLabel();
        yazarin_adi_label = new javax.swing.JLabel();
        yayin_evi_label = new javax.swing.JLabel();
        sayfa_numarasi_label = new javax.swing.JLabel();
        basim_yili_label = new javax.swing.JLabel();
        ISBN_num_label = new javax.swing.JLabel();
        fiyat_label = new javax.swing.JLabel();
        kitabin_turu_label = new javax.swing.JLabel();
        ekle_button = new java.awt.Button();
        fiyat_textfield = new javax.swing.JTextField();
        ISBN_num_textfield = new javax.swing.JTextField();
        basim_yili_textfield = new javax.swing.JTextField();
        sayfa_numarasi_textfield = new javax.swing.JTextField();
        yayin_evi_textfield = new javax.swing.JTextField();
        yazarin_adi_textfield = new javax.swing.JTextField();
        kitabin_adi_textfield = new javax.swing.JTextField();
        kitabin_numarasi_textfield = new javax.swing.JTextField();
        kitabin_turu_combo_box = new javax.swing.JComboBox<>();
        eklendi_textfield = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        back_button.setBackground(new java.awt.Color(255, 153, 0));
        back_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_button.setText("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        back_combo_box.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        back_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--SEC--]", "Klasik", "Bilgisayar", "Felsefe", "Dini", "Tarih", "Egitim" }));
        back_combo_box.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));

        jLabel1.setBackground(new java.awt.Color(153, 255, 51));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kitap Ekleme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setText(" Donmek istediginiz kategoriyi secin..");
        jLabel2.setToolTipText("Donmek istediginiz kategoriyi secin..");

        kitabin_numarasi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kitabin_numarasi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitabin_numarasi_label.setText("Kitabin Numarasi  : ");

        kitabin_adi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kitabin_adi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitabin_adi_label.setText("Kitabin Adi  :");

        yazarin_adi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yazarin_adi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yazarin_adi_label.setText("Yazarin Adi  :");

        yayin_evi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        yayin_evi_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yayin_evi_label.setText("Yayin Evi  :");
        yayin_evi_label.setToolTipText("");

        sayfa_numarasi_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sayfa_numarasi_label.setText("Sayfa Numarasi  :");

        basim_yili_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        basim_yili_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        basim_yili_label.setText("Basim Yili  :");

        ISBN_num_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ISBN_num_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ISBN_num_label.setText("ISBN Numarasi  :");

        fiyat_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fiyat_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fiyat_label.setText("Fiyat  :");

        kitabin_turu_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kitabin_turu_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitabin_turu_label.setText("Kitabin Turu  :");

        ekle_button.setBackground(new java.awt.Color(255, 255, 0));
        ekle_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ekle_button.setLabel("EKLE");
        ekle_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ekle_buttonMouseClicked(evt);
            }
        });
        ekle_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_buttonActionPerformed(evt);
            }
        });

        yayin_evi_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yayin_evi_textfieldActionPerformed(evt);
            }
        });

        kitabin_turu_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--SEC--]", "Klasikler", "Bilgisayar", "Felsefe", "Dini", "Tarih", "Egitim" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitabin_turu_label)
                            .addComponent(fiyat_label)
                            .addComponent(ISBN_num_label))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(back_combo_box, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                            .addComponent(ISBN_num_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basim_yili_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sayfa_numarasi_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yayin_evi_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(yazarin_adi_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitabin_adi_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitabin_numarasi_textfield, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(back_button))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(kitabin_turu_combo_box, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                        .addComponent(fiyat_textfield, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kitabin_numarasi_label)
                            .addComponent(kitabin_adi_label)
                            .addComponent(yazarin_adi_label)
                            .addComponent(yayin_evi_label)
                            .addComponent(sayfa_numarasi_label)
                            .addComponent(basim_yili_label)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(eklendi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(back_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_button))))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kitabin_numarasi_label)
                    .addComponent(kitabin_numarasi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kitabin_adi_label)
                    .addComponent(kitabin_adi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yazarin_adi_label)
                    .addComponent(yazarin_adi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(yayin_evi_label)
                    .addComponent(yayin_evi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sayfa_numarasi_label)
                    .addComponent(sayfa_numarasi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basim_yili_label)
                    .addComponent(basim_yili_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ISBN_num_label)
                    .addComponent(ISBN_num_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fiyat_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fiyat_label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(kitabin_turu_label)
                    .addComponent(kitabin_turu_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(ekle_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(eklendi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        if ( back_combo_box.getSelectedIndex() == 1 )
        {
            Klasik_Arayuz screen = new Klasik_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 2 )
        {
            Bilgisayar_Arayuz screen = new Bilgisayar_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 3 )
        {
            Felsefe_Arayuz screen = new Felsefe_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 4 )
        {
            Dini_Arayuz screen = new Dini_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 5 )
        {
            Tarih_Arayuz screen = new Tarih_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 6 )
        {
            Egitim_Arayuz screen = new Egitim_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_back_buttonActionPerformed

    private void yayin_evi_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yayin_evi_textfieldActionPerformed
    }//GEN-LAST:event_yayin_evi_textfieldActionPerformed

    private void ekle_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ekle_buttonMouseClicked
        DataBase db = new DataBase();
       
        String veri_tipi = null ;
        String kitabin_turu = null ;
        ArrayList<String> kitap_nesnesi = new ArrayList<>() ;
        
        String kitabin_numarasi_string = kitabin_numarasi_textfield.getText();
        kitap_nesnesi.add(kitabin_numarasi_string);
        
        String kitabin_adi = kitabin_adi_textfield.getText();
        kitap_nesnesi.add(kitabin_adi);
        
        String yazarin_adi = yazarin_adi_textfield.getText();
        kitap_nesnesi.add(yazarin_adi);
        
        String yayin_evi = yayin_evi_textfield.getText();
        kitap_nesnesi.add(yayin_evi);
        
        String sayfa_sayisi_string = sayfa_numarasi_textfield.getText();
        kitap_nesnesi.add(sayfa_sayisi_string);
         
        String basim_yili_string = basim_yili_textfield.getText();
        kitap_nesnesi.add(basim_yili_string); 
        
        String ISBN_num = ISBN_num_textfield.getText();
        kitap_nesnesi.add(ISBN_num);
        
        String fiyat_string = fiyat_textfield.getText();
        kitap_nesnesi.add(fiyat_string);
   
        int kitabin_turu_num = kitabin_turu_combo_box.getSelectedIndex();
        
        switch (kitabin_turu_num) {
            case 1:
                veri_tipi = "kitap_yayinciligi.Klasik";
                kitabin_turu = "Klasikler";
                break;
            case 2:
                veri_tipi = "kitap_yayinciligi.Bilgisayar";
                kitabin_turu = "Bilgisayar";
                break;
            case 3:
                veri_tipi = "kitap_yayinciligi.Felsefe";
                kitabin_turu = "Felsefe";
                break;
            case 4:
                veri_tipi = "kitap_yayinciligi.Dini";
                kitabin_turu = "Dini";
                break;
            case 5:
                veri_tipi = "kitap_yayinciligi.Tarih";
                kitabin_turu = "Tarih";
                break;
            case 6:
                veri_tipi = "kitap_yayinciligi.Egitim";
                kitabin_turu = "Egitim";
                break;
            default:
                break;
        }
        
        kitap_nesnesi.add(kitabin_turu);
        db.veri_ekleme(veri_tipi, kitap_nesnesi);
        db.eklenen_kitap_sayisi_degistir(veri_tipi,1);
        eklendi_textfield.setText("Yeni kitap basariyla eklendi..");
    }//GEN-LAST:event_ekle_buttonMouseClicked

    private void ekle_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_buttonActionPerformed
       
    }//GEN-LAST:event_ekle_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ekleme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ekleme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ekleme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_Ekleme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_Ekleme_Arayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ISBN_num_label;
    private javax.swing.JTextField ISBN_num_textfield;
    private javax.swing.JButton back_button;
    private javax.swing.JComboBox<String> back_combo_box;
    private javax.swing.JLabel basim_yili_label;
    private javax.swing.JTextField basim_yili_textfield;
    private java.awt.Button ekle_button;
    private javax.swing.JTextField eklendi_textfield;
    private javax.swing.JLabel fiyat_label;
    private javax.swing.JTextField fiyat_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel kitabin_adi_label;
    private javax.swing.JTextField kitabin_adi_textfield;
    private javax.swing.JLabel kitabin_numarasi_label;
    private javax.swing.JTextField kitabin_numarasi_textfield;
    private javax.swing.JComboBox<String> kitabin_turu_combo_box;
    private javax.swing.JLabel kitabin_turu_label;
    private javax.swing.JLabel sayfa_numarasi_label;
    private javax.swing.JTextField sayfa_numarasi_textfield;
    private javax.swing.JLabel yayin_evi_label;
    private javax.swing.JTextField yayin_evi_textfield;
    private javax.swing.JLabel yazarin_adi_label;
    private javax.swing.JTextField yazarin_adi_textfield;
    // End of variables declaration//GEN-END:variables
}
