/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kitap_yayinciligi;

/**
 *
 * @author CASPER
 */
public class Kitap_Silme_Arayuz extends javax.swing.JFrame {

    /**
     * Creates new form Kitap_Silme_Arayuz
     */
    public Kitap_Silme_Arayuz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        back_combo_box = new javax.swing.JComboBox<>();
        back_button = new java.awt.Button();
        jLabel5 = new javax.swing.JLabel();
        kitabin_numarasi_textfield = new javax.swing.JTextField();
        kitabin_turu_label = new javax.swing.JLabel();
        kitabin_turu_combo_box = new javax.swing.JComboBox<>();
        silme_button = new java.awt.Button();
        silme_yazisi_textfield = new javax.swing.JTextField();

        jLabel3.setText("jLabel3");

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 0));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Kitap Silme");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setText(" Donmek istediginiz kategoriyi secin..");

        back_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--SEC--]", "Klasik", "Bilgisayar", "Felsefe", "Dini", "Tarih", "Egitim" }));

        back_button.setBackground(new java.awt.Color(255, 153, 0));
        back_button.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        back_button.setLabel("BACK");
        back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_buttonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Silmek Istediginiz Kitabin Numarasini Giriniz : ");

        kitabin_turu_label.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        kitabin_turu_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        kitabin_turu_label.setText("Kitabin Turu  :");

        kitabin_turu_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "[--SEC--]", "Klasikler", "Bilgisayar", "Felsefe", "Dini", "Tarih", "Egitim" }));

        silme_button.setBackground(new java.awt.Color(255, 0, 0));
        silme_button.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        silme_button.setLabel("SIL");
        silme_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                silme_buttonMouseClicked(evt);
            }
        });
        silme_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silme_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(back_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(kitabin_numarasi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(kitabin_turu_label)
                                        .addGap(132, 132, 132)
                                        .addComponent(kitabin_turu_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(silme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(silme_yazisi_textfield)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(back_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(back_button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(kitabin_numarasi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kitabin_turu_label)
                    .addComponent(kitabin_turu_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62)
                .addComponent(silme_button, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(silme_yazisi_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_buttonActionPerformed
        if ( back_combo_box.getSelectedIndex() == 1 )
        {
            Klasik_Arayuz screen = new Klasik_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 2 )
        {
            Bilgisayar_Arayuz screen = new Bilgisayar_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 3 )
        {
            Felsefe_Arayuz screen = new Felsefe_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 4 )
        {
            Dini_Arayuz screen = new Dini_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 5 )
        {
            Tarih_Arayuz screen = new Tarih_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
        else if ( back_combo_box.getSelectedIndex() == 6 )
        {
            Egitim_Arayuz screen = new Egitim_Arayuz();
            screen.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_back_buttonActionPerformed

    private void silme_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_silme_buttonMouseClicked
        DataBase db = new DataBase();
        
        String veri_tipi = null ;
        int kitabin_turu_num = kitabin_turu_combo_box.getSelectedIndex();

        String kitabin_numarasi = kitabin_numarasi_textfield.getText();
        int kitabin_numarasi_int = Integer.parseInt(kitabin_numarasi);
        
        switch (kitabin_turu_num) {
            case 1:
                veri_tipi = "kitap_yayinciligi.Klasik";
                break;
            case 2:
                veri_tipi = "kitap_yayinciligi.Bilgisayar";
                break;
            case 3:
                veri_tipi = "kitap_yayinciligi.Felsefe";
                break;
            case 4:
                veri_tipi = "kitap_yayinciligi.Dini";
                break;
            case 5:
                veri_tipi = "kitap_yayinciligi.Tarih";
                break;
            case 6:
                veri_tipi = "kitap_yayinciligi.Egitim";
                break;
            default:
                break;
        }
        
        boolean sonuc = db.veri_silme(veri_tipi, kitabin_numarasi_int);
        
        if ( sonuc )
        {
            silme_yazisi_textfield.setText("Kitap basariyla silindi..");
            db.eklenen_kitap_sayisi_degistir(veri_tipi,0);
        }
        else
        {
            silme_yazisi_textfield.setText("Kitap silinemedi..");
        }
    }//GEN-LAST:event_silme_buttonMouseClicked

    private void silme_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silme_buttonActionPerformed

    }//GEN-LAST:event_silme_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kitap_Silme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kitap_Silme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kitap_Silme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kitap_Silme_Arayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kitap_Silme_Arayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button back_button;
    private javax.swing.JComboBox<String> back_combo_box;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kitabin_numarasi_textfield;
    private javax.swing.JComboBox<String> kitabin_turu_combo_box;
    private javax.swing.JLabel kitabin_turu_label;
    private java.awt.Button silme_button;
    private javax.swing.JTextField silme_yazisi_textfield;
    // End of variables declaration//GEN-END:variables
}
